import type { SessionEntry, SessionEntryRole } from './types.js';

interface ParsedTurnMetadata {
  requestId?: string;
  sourceMessageId?: string;
  role?: SessionEntryRole;
  speakerRole?: SessionEntryRole;
}

const LEGACY_INTENTION_AUTHOR_NAME = 'Intention Appraisal';

export interface NormalizedSessionEntryAttribution {
  role: SessionEntryRole;
  authorName?: string;
}

// ── Canonical group speaker attribution contract (charter Laws 17–19) ──
//
// In multi-speaker (non-private) conversation a user turn is rendered with a
// single text prefix:
//
//     DisplayName (stableId): <content>
//
// Provider chat formats do not carry portable per-message speaker metadata, so
// this text prefix — emitted OUTSIDE user-authored content — is the CANONICAL
// carrier of authorship. `formatGroupUserMessageContent` is the ONLY code
// allowed to construct that prefix and `parseGroupUserMessageContent` the only
// code allowed to interpret it.
//
// TRUST RULE:
//   * Only a prefix produced by `formatGroupUserMessageContent` is
//     authoritative, because it is generated by the runtime, never by a speaker.
//   * `stableId` is the trustworthy identity anchor. `DisplayName` is cosmetic
//     and attacker-influenced; it is sanitized but MUST NOT be trusted for
//     identity decisions.
//   * Any prefix-shaped text appearing INSIDE user content is untrusted and is
//     neutralized by `escapeAttributionForgery` so it can never masquerade as a
//     real speaker.

export interface GroupUserAttributionInput {
  authorId?: string;
  authorName?: string;
  channelId?: string;
  source?: string;
}

export interface ParsedGroupUserMessage {
  displayName: string;
  stableId: string;
  content: string;
}

const DISCORD_SNOWFLAKE_ID = /^\d{15,25}$/;

// A rendered line is "prefix-shaped" when a reader could mistake it for a
// genuine attribution prefix: `<name> (<token>): …` where neither the name nor
// the token contains a parenthesis. Leading whitespace is allowed so that
// indentation tricks cannot smuggle a forged prefix past the guard.
const ATTRIBUTION_PREFIX_LINE = /^(\s*)([^()\n]+) \(([^()\n]+)\): /;

// Parses exactly one canonical prefix off the front of a rendered value.
const CANONICAL_PREFIX = /^([^()\n]+) \(([^()\n]+)\):(?: ([\s\S]*))?$/;

function trimToUndefined(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed && trimmed.length > 0 ? trimmed : undefined;
}

// Strip C0/C1 control characters, DEL, and Unicode format/bidi/zero-width
// characters (Cf) that could hide or reorder attribution text.
function stripUnsafeChars(value: string): string {
  return value
    // C0 controls, DEL, and C1 controls.
    // eslint-disable-next-line no-control-regex
    .replace(/[\u0000-\u001F\u007F-\u009F]/g, '')
    // Zero-width, bidi overrides, and other Unicode format (Cf) characters.
    .replace(/[\u200B-\u200F\u202A-\u202E\u2060-\u206F\uFEFF]/g, '');
}

// Display names are cosmetic. Neutralize every delimiter that could break the
// prefix grammar or forge a speaker: parentheses (label boundary) and colons
// (separator). Unicode confusables cannot be fully defeated here — the stableId
// remains the trust anchor — but control/format chars and delimiters are
// stripped so a name can never break out of its slot.
export function sanitizeAttributionDisplayName(value: string | undefined): string | undefined {
  if (typeof value !== 'string') return undefined;
  const cleaned = stripUnsafeChars(value.normalize('NFC'))
    .replace(/[()]/g, ' ')
    .replace(/:/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  return cleaned.length > 0 ? cleaned : undefined;
}

// Stable ids are the trust anchor. They must never contain a parenthesis (which
// closes the label) or whitespace. The source separator ':' is preserved.
function sanitizeStableId(value: string): string {
  const cleaned = stripUnsafeChars(value.normalize('NFC'))
    .replace(/[()]/g, '')
    .replace(/\s+/g, '')
    .trim();
  return cleaned.length > 0 ? cleaned : 'unknown';
}

function inferAuthorSourceFromChannelId(channelId: string | undefined): string | undefined {
  const normalized = trimToUndefined(channelId);
  if (!normalized) return undefined;
  if (normalized.startsWith('discord-voice:')) return 'discord';
  if (DISCORD_SNOWFLAKE_ID.test(normalized)) return 'discord';

  const separatorIndex = normalized.indexOf(':');
  if (separatorIndex <= 0) return undefined;
  const prefix = normalized.slice(0, separatorIndex).trim();
  if (!prefix) return undefined;
  return prefix === 'discord-voice' ? 'discord' : prefix;
}

function formatStableAuthorId(input: GroupUserAttributionInput): string {
  const authorId = trimToUndefined(input.authorId);
  const source = trimToUndefined(input.source) ?? inferAuthorSourceFromChannelId(input.channelId);
  const raw = !authorId
    ? (source ? `${source}:unknown` : 'unknown')
    : (!source || authorId.startsWith(`${source}:`) ? authorId : `${source}:${authorId}`);
  return sanitizeStableId(raw);
}

/** Build the sanitized `DisplayName (stableId)` label. stableId is always present. */
export function formatGroupUserAttributionLabel(input: GroupUserAttributionInput): string {
  const stableAuthorId = formatStableAuthorId(input);
  const displayName = sanitizeAttributionDisplayName(input.authorName) ?? stableAuthorId;
  return `${displayName} (${stableAuthorId})`;
}

/**
 * Neutralize prefix-shaped lines inside user-authored content so they cannot be
 * read as an authoritative speaker prefix. The parentheses of a forged label are
 * escaped, which breaks the grammar while keeping the text human-readable.
 */
export function escapeAttributionForgery(content: string): string {
  return content
    .split('\n')
    .map(line => line.replace(
      ATTRIBUTION_PREFIX_LINE,
      (_match, lead: string, name: string, id: string) => `${lead}${name} \\(${id}\\): `,
    ))
    .join('\n');
}

/**
 * Render a user turn with its canonical, authoritative attribution prefix.
 *
 * The prefix is always (re)built by the runtime from the known author identity,
 * and the body is always guarded against forgery. If the content already carries
 * THIS author's exact prefix it is not nested a second time (idempotent), but
 * the remainder is still guarded so a trailing forged speaker line cannot slip
 * through.
 */
export function formatGroupUserMessageContent(
  content: string,
  input: GroupUserAttributionInput,
): string {
  const label = formatGroupUserAttributionLabel(input);
  const prefixWithSpace = `${label}: `;
  const bareLabel = `${label}:`;

  let body = content;
  if (body.startsWith(prefixWithSpace)) {
    body = body.slice(prefixWithSpace.length);
  } else if (body.startsWith(bareLabel)) {
    body = body.slice(bareLabel.length);
  }

  const guarded = escapeAttributionForgery(body).trim();
  return guarded.length > 0 ? `${label}: ${guarded}` : bareLabel;
}

/**
 * Parse the canonical prefix off a rendered value. For tooling and tests only;
 * runtime trust decisions never depend on parsing a rendered string back.
 * Returns null when the value does not begin with a well-formed prefix.
 */
export function parseGroupUserMessageContent(rendered: string): ParsedGroupUserMessage | null {
  const match = CANONICAL_PREFIX.exec(rendered);
  if (!match) return null;
  // The content group is optional, so at runtime it may be undefined even though
  // RegExpExecArray types every element as `string`.
  const parsedContent = match[3] as string | undefined;
  return {
    displayName: match[1].trim(),
    stableId: match[2].trim(),
    content: parsedContent ?? '',
  };
}

function parseTurnMetadata(metadata: string | undefined): ParsedTurnMetadata {
  if (!metadata) return {};

  let parsed: unknown;
  try {
    parsed = JSON.parse(metadata);
  } catch {
    return {};
  }

  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return {};
  }

  const rawTurn = (parsed as Record<string, unknown>).turn;
  if (!rawTurn || typeof rawTurn !== 'object' || Array.isArray(rawTurn)) {
    return {};
  }

  const turn = rawTurn as Record<string, unknown>;
  const requestId = typeof turn.requestId === 'string' ? turn.requestId.trim() : '';
  const sourceMessageId = typeof turn.sourceMessageId === 'string' ? turn.sourceMessageId.trim() : '';
  const role = typeof turn.role === 'string' && (
    turn.role === 'user'
    || turn.role === 'assistant'
    || turn.role === 'system'
    || turn.role === 'tool'
  )
    ? turn.role
    : undefined;
  const speakerRole = typeof turn.speakerRole === 'string' && (
    turn.speakerRole === 'user'
    || turn.speakerRole === 'assistant'
    || turn.speakerRole === 'system'
    || turn.speakerRole === 'tool'
  )
    ? turn.speakerRole
    : undefined;

  return {
    ...(requestId ? { requestId } : {}),
    ...(sourceMessageId ? { sourceMessageId } : {}),
    ...(role ? { role } : {}),
    ...(speakerRole ? { speakerRole } : {}),
  };
}

function startsWithIntentionFollowUp(value: string | undefined): boolean {
  return typeof value === 'string' && value.startsWith('intention-follow-up:');
}

function startsWithReflectionRequest(value: string | undefined): boolean {
  return typeof value === 'string' && value.startsWith('reflection-');
}

function hasIntentionPrefix(content: string): boolean {
  return content.startsWith('[Intention Appraisal]')
    || content.startsWith('[SYSTEM: Intention Appraisal]');
}

function stripBracketedPrefix(content: string, label: string): string {
  const trimmed = content.trimStart();
  const prefix = `[${label}]`;
  if (!trimmed.startsWith(prefix)) {
    return content;
  }

  const remainder = trimmed.slice(prefix.length).trimStart();
  return remainder || content;
}

export function isIntentionAppraisalArtifact(
  entry: Pick<SessionEntry, 'content' | 'authorId' | 'authorName' | 'metadata'>
    & Partial<ParsedTurnMetadata>,
): boolean {
  const parsedTurn = parseTurnMetadata(entry.metadata);
  const turn: ParsedTurnMetadata = {
    ...parsedTurn,
    ...(typeof entry.requestId === 'string' && entry.requestId.trim().length > 0
      ? { requestId: entry.requestId.trim() }
      : {}),
    ...(typeof entry.sourceMessageId === 'string' && entry.sourceMessageId.trim().length > 0
      ? { sourceMessageId: entry.sourceMessageId.trim() }
      : {}),
  };
  const authorId = entry.authorId?.trim() ?? '';
  const authorName = entry.authorName?.trim() ?? '';
  const content = entry.content.trimStart();

  return (
    authorId.startsWith('system:')
    || authorName === LEGACY_INTENTION_AUTHOR_NAME
    || startsWithIntentionFollowUp(turn.requestId)
    || startsWithIntentionFollowUp(turn.sourceMessageId)
    || hasIntentionPrefix(content)
  );
}

export function normalizeSessionEntryAttribution(
  entry: Pick<SessionEntry, 'role' | 'content' | 'authorId' | 'authorName' | 'metadata' | 'channelId'>
    & Partial<ParsedTurnMetadata>,
): NormalizedSessionEntryAttribution {
  if (entry.role === 'tool') {
    return { role: 'tool', authorName: entry.authorName };
  }

  const parsedTurn = parseTurnMetadata(entry.metadata);
  const turn: ParsedTurnMetadata = {
    ...parsedTurn,
    ...(typeof entry.requestId === 'string' && entry.requestId.trim().length > 0
      ? { requestId: entry.requestId.trim() }
      : {}),
    ...(typeof entry.sourceMessageId === 'string' && entry.sourceMessageId.trim().length > 0
      ? { sourceMessageId: entry.sourceMessageId.trim() }
      : {}),
  };
  const authorId = entry.authorId?.trim() ?? '';
  const authorName = entry.authorName?.trim() ?? '';

  const explicitSpeakerRole = turn.speakerRole;
  if (explicitSpeakerRole && explicitSpeakerRole !== 'tool') {
    return {
      role: explicitSpeakerRole === 'assistant' ? 'assistant' : explicitSpeakerRole === 'system' ? 'system' : 'user',
      ...(authorName ? { authorName } : {}),
    };
  }

  if (isIntentionAppraisalArtifact(entry)) {
    return {
      role: 'system',
      authorName: LEGACY_INTENTION_AUTHOR_NAME,
    };
  }

  const isScheduledInternalPrompt = (
    authorId === 'scheduler'
    || (
      entry.channelId.startsWith('internal:')
      && (startsWithReflectionRequest(turn.requestId) || startsWithReflectionRequest(turn.sourceMessageId))
    )
  );
  if (isScheduledInternalPrompt) {
    return {
      role: 'system',
      authorName: authorName || 'Scheduler',
    };
  }

  if (entry.role === 'system') {
    return {
      role: 'system',
      ...(authorName ? { authorName } : {}),
    };
  }

  return {
    role: entry.role === 'assistant' ? 'assistant' : 'user',
    ...(authorName ? { authorName } : {}),
  };
}

/**
 * Write-time authorship integrity detector (charter laws 17/19, section 8.2).
 *
 * The read-time normalizer above re-tags known internal signatures when
 * building context, but that alone lets a mistagged entry persist as partner
 * speech and regress whenever a new internal system forgets its provenance.
 * This detector lets the session manager refuse user attribution for
 * internal-origin entries at append time, so internal messages can never be
 * stored as if the partner authored them.
 */
export function detectInternalOriginForUserAttribution(
  entry: Pick<SessionEntry, 'content' | 'authorId' | 'authorName' | 'metadata' | 'channelId'>
    & Partial<ParsedTurnMetadata>,
): string | null {
  const authorId = entry.authorId?.trim() ?? '';
  if (authorId === 'scheduler') return 'scheduler_author';
  if (authorId.startsWith('system:')) return 'system_author_prefix';
  if (authorId.startsWith('internal:')) return 'internal_author_prefix';

  if (isIntentionAppraisalArtifact(entry)) return 'intention_appraisal_artifact';

  const parsedTurn = parseTurnMetadata(entry.metadata);
  const requestId = typeof entry.requestId === 'string' && entry.requestId.trim().length > 0
    ? entry.requestId.trim()
    : parsedTurn.requestId;
  const sourceMessageId = typeof entry.sourceMessageId === 'string' && entry.sourceMessageId.trim().length > 0
    ? entry.sourceMessageId.trim()
    : parsedTurn.sourceMessageId;
  if (
    entry.channelId.startsWith('internal:')
    && (startsWithReflectionRequest(requestId) || startsWithReflectionRequest(sourceMessageId))
  ) {
    return 'internal_reflection_request';
  }

  return null;
}

export function formatAttributedSystemContent(content: string, authorName?: string): string {
  const trimmed = content.trim();
  if (!trimmed) return content;
  if (trimmed.startsWith('[SYSTEM:')) return trimmed;
  if (trimmed.startsWith('[System note]')) return trimmed;
  if (trimmed.startsWith('[Mirror note')) return trimmed;

  const label = authorName?.trim() || 'System';
  const normalizedContent = stripBracketedPrefix(trimmed, label);
  return `[SYSTEM: ${label}] ${normalizedContent}`;
}
