import type { RuntimeFallbackProvenance } from '../../shared/contracts/runtime.js';
import { normalizeRuntimeFallbackProvenance } from '../../shared/runtime-fallback-provenance.js';
import { isRecord } from '../../shared/utils/types.js';
import type { SessionEntry } from './types.js';

export const SESSION_METADATA_RUNTIME_FALLBACK_PROVENANCE_KEY = 'runtimeFallbackProvenance';

interface SessionMetadataEnvelope {
  [key: string]: unknown;
}

function parseMetadataEnvelope(metadata: string | undefined): SessionMetadataEnvelope {
  if (!metadata) return {};

  let parsed: unknown;
  try {
    parsed = JSON.parse(metadata);
  } catch {
    throw new Error('Session metadata is malformed JSON; refusing runtime fallback provenance parsing');
  }
  if (!isRecord(parsed)) {
    throw new Error('Session metadata must be a JSON object for runtime fallback provenance parsing');
  }
  return parsed;
}

export function buildSessionMetadataWithRuntimeFallbackProvenance(
  existingMetadata: string | undefined,
  provenance: RuntimeFallbackProvenance,
): string {
  const base = parseMetadataEnvelope(existingMetadata);
  return JSON.stringify({
    ...base,
    [SESSION_METADATA_RUNTIME_FALLBACK_PROVENANCE_KEY]: normalizeRuntimeFallbackProvenance(provenance),
  });
}

export function parseSessionRuntimeFallbackProvenance(
  metadata: string | undefined,
): RuntimeFallbackProvenance | null {
  const envelope = parseMetadataEnvelope(metadata);
  const raw = envelope[SESSION_METADATA_RUNTIME_FALLBACK_PROVENANCE_KEY];
  return raw === undefined
    ? null
    : normalizeRuntimeFallbackProvenance(raw, `metadata.${SESSION_METADATA_RUNTIME_FALLBACK_PROVENANCE_KEY}`);
}

/**
 * True when a persisted session entry was authored by the runtime fallback
 * path rather than generated by the companion (psfn-framework-zagpk, charter
 * Law 17). Memory extraction and any other companion self-report consumer must
 * treat such entries as runtime speech, never as her own words.
 *
 * Semantics are deliberately key-presence based and fail closed for
 * consent-grade data: an entry that carries the
 * `runtimeFallbackProvenance` marker at all — even with a malformed value — is
 * runtime-authored and excluded from self-report. Metadata that is missing or
 * unreadable JSON returns false, matching the lenient envelope behavior of the
 * sibling session-entry predicates (`isNonConversationalSessionEntry`):
 * unreadable metadata is not evidence of runtime authorship, and this
 * read-side predicate must not throw over historical rows.
 */
export function isRuntimeAuthoredFallbackSessionEntry(
  entry: Pick<SessionEntry, 'metadata'>,
): boolean {
  if (!entry.metadata) return false;

  let parsed: unknown;
  try {
    parsed = JSON.parse(entry.metadata);
  } catch {
    return false;
  }
  if (!isRecord(parsed)) return false;
  return parsed[SESSION_METADATA_RUNTIME_FALLBACK_PROVENANCE_KEY] !== undefined;
}
