import { action, type CanonicalToolSurfaceContract } from './contracts.js';

const PERSONA_FIELDS = [
  'name', 'description', 'personality', 'scenario', 'first_mes', 'mes_example',
  'system_prompt', 'post_history_instructions', 'tags', 'creator', 'creator_notes',
  'alternate_greetings', 'extensions_visual_description', 'extensions.visual_description',
] as const;

export const CONTINUITY_TOOL_CONTRACTS = {
  orient: {
    purpose: 'Maintain scoped continuity blocks, values, open threads, and explicit introspection consent choices.',
    actions: [
      action('append', ['block', 'text'], ['separator']),
      action('replace', ['block', 'text']),
      action('reorient', ['persona', 'human', 'goals'], [], { id: 'reorient', rule: 'all three are complete replacement strings' }),
      action('values_list', [], ['limit']),
      action('values_add', ['value'], ['context']),
      action('values_update', ['version', 'value'], ['context']),
      action('create_concern', ['text'], ['priority', 'status', 'salience', 'sensitivity', 'owner', 'evidenceRefs', 'reopenResolved', 'nextReviewAt', 'contactId', 'source']),
      action('list_concerns', [], ['contactId', 'includeResolved', 'includeExpired', 'limit']),
      action('resolve_concern', [], ['outcome', 'evidenceRefs'], { id: 'resolve_concern', requiredAnyOf: [['concernId'], ['concernIds']] }),
      action('transition_concern', ['status'], ['outcome', 'evidenceRefs', 'nextReviewAt', 'clearNextReview', 'salience'], { id: 'transition_concern', requiredAnyOf: [['concernId'], ['concernIds']] }),
      action('introspection_consent_get'),
      action('introspection_consent_set', ['enabled'], ['allowedPublicChannelIds', 'reason'], { id: 'introspection_consent_set', rule: 'requires an active foreground companion turn' }),
      action('introspection_turn_sensitivity_set', ['auditContentSensitivity'], [], { id: 'introspection_turn_sensitivity_set', rule: 'classifies the exact active foreground turn' }),
    ],
    output: 'It writes scoped orientation state and returns exact IDs, revisions, or consent state without redefining identity.',
    guidance: 'Do not store durable facts here; use memory, north_star, or identity for their respective domains.',
    example: { action: 'create_concern', text: 'Check whether the promised follow-up happened tomorrow.', priority: 'medium' },
  },
  identity: {
    purpose: 'Inspect and deliberately revise prompt layers or character-card persona fields through the audited identity boundary.',
    actions: [
      action('list_layers'),
      action('get_layer', ['layer_id']),
      action('diff_layer', ['layer_id'], ['version', 'max_diff_lines']),
      action('history', [], ['layer_id', 'limit']),
      action('update_layer', ['layer_id', 'content'], ['reason']),
      action('rollback_layer', ['layer_id', 'version'], ['reason']),
      action('toggle_layer', ['layer_id']),
      action('update_persona', [], ['reason', 'allow_destructive_replace'], { id: 'update_persona', requiredOneOf: PERSONA_FIELDS }),
      action('commit_stage', ['stage_id'], ['reason']),
      action('cancel_stage', ['stage_id'], ['reason']),
    ],
    output: 'It returns layer, diff, revision, persona, or staged-change state and never bypasses safeguards.',
    guidance: 'Do not use identity for current open threads or long-horizon intent; use orient or north_star.',
    example: { action: 'diff_layer', layer_id: 'runtime', version: 2 },
  },
  memory: {
    purpose: 'Store and retrieve durable typed memories that should survive beyond the current session.',
    actions: [
      action('write', ['text', 'type'], ['importance', 'emotional_valence', 'confidence', 'tags', 'sensitivity', 'formation_vad']),
      action('search', ['query'], ['limit']),
      action('episode_search', ['query'], ['limit', 'channel_id', 'trust_level', 'channel_visibility', 'canonical_contact_id'], {
        id: 'episode_search',
        rule: 'lexically searches visible canonical episodes and returns exact episode ids for action=get drill-down',
      }),
      action('get', ['episode_id'], ['limit', 'channel_id', 'trust_level', 'channel_visibility', 'canonical_contact_id'], {
        id: 'get',
        rule: 'expands the exact visible episode into journal-current source turns plus visible arc and thread siblings',
      }),
      action('shared_background', ['contact_a', 'contact_b']),
      action('census', [], ['contact_id', 'scope_kind', 'scope_id', 'scope_tag', 'include_archived', 'channel_id', 'trust_level', 'channel_visibility', 'canonical_contact_id']),
      action('exists', ['query'], ['contact_id', 'scope_kind', 'scope_id', 'scope_tag', 'include_archived', 'channel_id', 'trust_level', 'channel_visibility', 'canonical_contact_id']),
      action('timeline', [], ['date', 'after', 'before', 'limit', 'channel_id', 'trust_level', 'channel_visibility', 'canonical_contact_id']),
      action('import', ['records'], ['source']),
      action('patch', ['memory_id'], ['text', 'importance', 'emotional_valence', 'confidence', 'tags', 'append_tags', 'formation_vad', 'clear_formation_vad', 'reason']),
      action('redact', ['memory_id'], ['operation', 'reason'], {
        id: 'redact',
        rule: 'retired because redaction removes active memory; use the justified deletion proposal action',
      }),
      action('delete', ['memory_id', 'justification_category', 'explanation'], [], {
        id: 'delete',
        rule: 'creates a durable Partner-alerted proposal; only an authenticated Operator approval applies the reversible soft delete',
      }),
      action('restore', ['delete_id']),
    ],
    output: 'It returns exact memory, episode-turn, event, deletion-proposal, delete, or provenance identifiers instead of changing unrelated records silently.',
    guidance: 'Use episode_search for deliberate event recall, then get with an exact returned episode ID for source-turn evidence. Do not use durable memory as a scratch file, journal, transcript index, or reference wiki.',
    example: { action: 'episode_search', query: 'the planter repair', limit: 5 },
  },
  scratchpad: {
    purpose: 'Keep temporary working notes and excerpts that may expire after the current day.',
    actions: [
      action('list', [], ['limit']), action('add', ['content']),
      action('replace', ['id', 'content']), action('append', ['id', 'content']),
      action('remove', ['id']),
    ],
    output: 'It returns ephemeral note IDs and never creates a durable reminder or stable memory.',
    guidance: 'Do not use it for lasting facts or authored notes; use memory or journal.',
    example: { action: 'add', content: 'Compare the two deployment logs after the next run.' },
  },
  contact: {
    purpose: 'Read and deliberately maintain canonical people, relationship state, identities, privacy, blocks, and known-peer availability.',
    actions: [
      action('list'), action('search', ['query']), action('lookup', ['contactId']),
      action('note', ['contactId', 'notes']),
      action('set_trust', ['contactId'], ['trustLevel', 'behaviorSignals', 'confirmSuggestion'], { id: 'set_trust', rule: 'requires trustLevel or behaviorSignals and cannot directly set high-tier trust' }),
      action('propose_trust', ['contactId', 'rationale'], ['trustLevel'], { id: 'propose_trust', rule: 'only proposes trusted for operator approval' }),
      action('set_relationship', ['contactId', 'relationshipType']),
      action('propose_relationship', ['contactId', 'relationshipType', 'rationale']),
      action('link_identity', ['contactId', 'channel', 'channelUserId'], ['privacyLevel']),
      action('set_channel_privacy', ['contactId', 'channel', 'channelUserId', 'privacyLevel']),
      action('set_machine_intelligence', ['contactId', 'isMachineIntelligence']),
      action('block', [], ['blockMode', 'blockScope', 'reason'], { id: 'block', requiredAnyOf: [['contactId'], ['channel', 'channelUserId']] }),
      action('unblock', [], ['reason'], { id: 'unblock', requiredAnyOf: [['contactId'], ['channel', 'channelUserId']] }),
    ],
    output: 'It returns exact contact or audit state and never infers high trust or intimacy from caller-supplied counts.',
    guidance: 'Do not use contact as event memory or outbound delivery; use memory or notify.',
    example: { action: 'lookup', contactId: 'contact-123' },
  },
  session: {
    purpose: 'Navigate conversation continuity, transcript evidence, wake summaries, and bounded focus work.',
    actions: [
      action('list', [], ['limit']), action('new', [], ['metadata']),
      action('resume', ['sessionId']), action('search', ['query'], ['limit', 'channelId', 'summarize']),
      action('grep', ['pattern'], ['mode', 'caseSensitive', 'limit', 'channelId']),
      action('wake_return', ['summary'], ['sessionId', 'nextAnchor', 'facets', 'occasion']),
      action('start_focus', ['scope'], ['channelId']), action('complete_focus', [], ['conclusion']),
    ],
    output: 'It returns exact session, evidence, continuity-artifact, or focus identifiers rather than preview text.',
    guidance: 'Do not treat transcript search as durable memory or a scratchpad; use memory or scratchpad.',
    example: { action: 'search', query: 'promise about the vet appointment', limit: 5 },
  },
} as const satisfies Record<string, CanonicalToolSurfaceContract>;
