import type { MemoryStore } from './store.js';

export type MemoryStorePort = Pick<
  MemoryStore,
  | 'insertMemory'
  | 'runInTransaction'
  | 'searchByEmbedding'
  | 'searchByText'
  | 'updateMemory'
  | 'getAllActiveMemories'
  | 'listActiveMemories'
  | 'countActiveMemories'
  | 'getById'
  | 'softDeleteMemory'
  | 'undoSoftDelete'
  | 'getDeleteVersion'
  | 'recordAbstractionLink'
  | 'getAbstractionLinksForSourceMemory'
  | 'getAbstractionLinksForAbstractedMemory'
  | 'getStats'
  | 'getMemoriesByChannel'
  | 'getMemoriesByContact'
  | 'linkMemories'
  | 'unlinkMemories'
  | 'getLinkedMemories'
  | 'bulkDelete'
  | 'bulkUpdate'
  | 'upsertContactProfile'
  | 'getContactProfile'
  | 'listContactProfiles'
  | 'addScratchpadEntry'
  | 'replaceScratchpadEntry'
  | 'appendScratchpadEntry'
  | 'removeScratchpadEntry'
  | 'getScratchpadEntry'
  | 'listScratchpadEntries'
>;
