apiVersion: v1
kind: Secret
metadata:
  name: psfn-secrets
  namespace: psfn
  labels:
    app.kubernetes.io/part-of: psfn
type: Opaque
stringData:
  OPENROUTER_API_KEY: ""
  API_KEY: ""
  ADMIN_TOKEN: ""
  # DISCORD_TOKEN: ""
  # DISCORD_BOT_ID: ""
  # TELEGRAM_BOT_TOKEN: ""
  # DEEPGRAM_API_KEY: ""
  # ELEVENLABS_API_KEY: ""
  # DATABASE_URL: "postgres://psfn:changeme@postgres:5432/psfn"
  # HF_TOKEN: ""
