apiVersion: v1
kind: Service
metadata:
  name: psfn-api
  namespace: psfn
  labels:
    app.kubernetes.io/name: psfn
    app.kubernetes.io/part-of: psfn
spec:
  selector:
    app.kubernetes.io/name: psfn
  ports:
    - name: api
      port: 3000
      targetPort: api
      protocol: TCP
    - name: admin
      port: 3001
      targetPort: admin
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: psfn
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/part-of: psfn
spec:
  selector:
    app.kubernetes.io/name: litellm
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tei
  namespace: psfn
  labels:
    app.kubernetes.io/name: tei
    app.kubernetes.io/part-of: psfn
spec:
  selector:
    app.kubernetes.io/name: tei
  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: psfn
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: psfn
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: tcp
      port: 5432
      targetPort: tcp
      protocol: TCP
  type: ClusterIP
  clusterIP: None
